name: Hprofile Actions

on:
  workflow_dispatch

jobs:
  Testing:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Code checkout
        uses: actions/checkout@v4

      # Set up Java 11
      - name: Set Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Install dependencies and run tests
      - name: Maven install and test
        run: mvn clean install

      # Run Checkstyle
      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      # Check network connectivity (via curl instead of ping)
      - name: Check Network Connectivity
        run: curl -v https://sonarcloud.io/api/health

      # Setup sonar-scanner
      - name: Setup SonarQube Scanner
        uses: warchant/setup-sonar-scanner@v7

      # Run SonarQube Scan
      - name: SonarQube