name: Hprofile Actions

on: 
  workflow_dispatch

jobs:
  Testing:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Code checkout
        uses: actions/checkout@v4

      # Set up Java 11
      - name: Set Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Install dependencies and run tests
      - name: Maven test
        run: mvn clean install

      # Checkstyle
      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      # Check network connectivity (via curl instead of ping)
      - name: Check Network Connectivity
        run: curl -v https://sonarcloud.io/api/health

      # Setup sonar-scanner
      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7

      # Run SonarQube Scan
      - name: SonarQube Scan
        run: |
          sonar-scanner \
          -Dsonar.host.url=${{ secrets.SONAR_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
          -Dsonar.sources=src/ \
          -Dsonar.junit.reportsPath=target/surefire-reports/ \
          -Dsonar.jacoco.reportsPath=target/jacoco.exec \
          -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml \
          -Dsonar.java.binaries=target/classes


